name: CI
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: create env
        run: echo "${{secrets.ENVS}}" > .env
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Docker build & push to prod
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fictionholic .
          docker push ${{ secrets.DOCKER_USERNAME }}/fictionholic
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_IP}}
          username: ubuntu
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          script: |
            mkdir -p ./config
            echo "${{secrets.ENVS}}" > ./config/.env
            docker ps 
            docker container stop app
            docker pull ${{ secrets.DOCKER_USERNAME }}/fictionholic
            docker run -d -p 8080:8080 --env-file ~/config/.env -e TZ=Asia/Seoul --name app ${{ secrets.DOCKER_USERNAME }}/fictionholic
            docker image prune -f
